# Generated by Django 2.2.8 on 2020-06-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200610_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='lable',
        ),
        migrations.AddField(
            model_name='item',
            name='lable',
            field=models.ManyToManyField(to='app1.Lables'),
        ),
    ]
