# Generated by Django 2.2.8 on 2020-06-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
